package com.photosmcp.locationbridge;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;

final class OutboxDb extends SQLiteOpenHelper {
    static final class Batch {
        final long rowId;
        final long sequence;
        final String idempotencyKey;
        final String payload;

        Batch(long rowId, long sequence, String idempotencyKey, String payload) {
            this.rowId = rowId;
            this.sequence = sequence;
            this.idempotencyKey = idempotencyKey;
            this.payload = payload;
        }
    }

    OutboxDb(Context context) {
        super(context, "location-outbox.sqlite3", null, 1);
    }

    @Override public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE batches (id INTEGER PRIMARY KEY AUTOINCREMENT," +
                " sequence INTEGER NOT NULL UNIQUE, idempotency_key TEXT NOT NULL UNIQUE," +
                " ciphertext BLOB NOT NULL, nonce BLOB NOT NULL, created_at INTEGER NOT NULL)");
    }

    @Override public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {}

    synchronized void enqueue(long sequence, String payload) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        // Android Keystore requires encryption IVs to be generated by the
        // cryptographic provider. Persist that unique IV beside the ciphertext.
        cipher.init(Cipher.ENCRYPT_MODE, BridgeKeys.outboxKey());
        byte[] nonce = cipher.getIV();
        ContentValues values = new ContentValues();
        values.put("sequence", sequence);
        values.put("idempotency_key", "mobile_" + UUID.randomUUID());
        values.put("ciphertext", cipher.doFinal(payload.getBytes(StandardCharsets.UTF_8)));
        values.put("nonce", nonce);
        values.put("created_at", System.currentTimeMillis());
        getWritableDatabase().insertOrThrow("batches", null, values);
    }

    synchronized List<Batch> pending() throws Exception {
        List<Batch> result = new ArrayList<>();
        try (Cursor cursor = getReadableDatabase().rawQuery(
                "SELECT id, sequence, idempotency_key, ciphertext, nonce FROM batches ORDER BY sequence", null)) {
            while (cursor.moveToNext()) {
                Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
                cipher.init(Cipher.DECRYPT_MODE, BridgeKeys.outboxKey(),
                        new GCMParameterSpec(128, cursor.getBlob(4)));
                String payload = new String(cipher.doFinal(cursor.getBlob(3)), StandardCharsets.UTF_8);
                result.add(new Batch(cursor.getLong(0), cursor.getLong(1), cursor.getString(2), payload));
            }
        }
        return result;
    }

    synchronized void acknowledge(long rowId) {
        getWritableDatabase().delete("batches", "id = ?", new String[]{Long.toString(rowId)});
    }

    synchronized int count() {
        try (Cursor cursor = getReadableDatabase().rawQuery("SELECT COUNT(*) FROM batches", null)) {
            cursor.moveToFirst();
            return cursor.getInt(0);
        }
    }
}
